###################################
# truenative
###################################
apiVersion: apps/v1
kind: Deployment
metadata:
  name: truenative
  labels:
    app: truenative
spec:
  replicas: 1
  selector:
    matchLabels:
      app: truenative
  template:
    metadata:
      labels:
        app: truenative
    spec:
      containers:
        - name: truenative
          image: ghcr.io/misw-4301-desarrollo-apps-en-la-nube/true-native:1.0.0
          ports:
            - containerPort: 4000
          imagePullPolicy: Always
          env:
            - name: "EXPRESS_RATE"
              value: "1"
            - name: "SECRET_TOKEN"
              value: "D2hVX^2Z60HaQX5*9eZW"
            - name: "BASIC_DELAY"
              value: "30"

---
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: truenative-config
spec:
  healthCheck:
    checkIntervalSec: 30
    port: 4000
    type: HTTP
    requestPath: /ping
---
kind: Service
apiVersion: v1
metadata:
  name: servicio-truenative
  annotations:
    cloud.google.com/backend-config: '{"default": "truenative-config"}'
spec:
  type: NodePort
  selector:
    app: truenative
  ports:
    - protocol: TCP
      port: 80
      targetPort: 4000
      nodePort: 31018
